# Generated by Django 6.1 on 2026-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_category_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='started_client_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='started_worker_bot',
            field=models.BooleanField(default=False),
        ),
    ]
