# Generated by Django 6.1 on 2026-09-02 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_job_credits_user_started_client_bot_and_more'),
        ('categories', '0002_alter_category_options_remove_category_description_and_more'),
        ('locations', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Boshqa soha (qo'lda kiritilgan)"),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Boshqa lavozim (qo'lda kiritilgan)"),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha (Lotin)"), ('oz', 'Ўзбекча (Кирилл)'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='categories.position', verbose_name='Lavozim / Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.region', verbose_name='Viloyat / Hudud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='categories.category', verbose_name="Soha / Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CALL_CENTER', 'Call Center Operator'), ('WORKER', 'Ish qidiruvchi / Usta / Xodim'), ('CLIENT', 'Ish beruvchi / Mijoz')], default='WORKER', max_length=20),
        ),
    ]
