# Generated by Django 6.1 on 2026-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_custom_category_user_custom_position_and_more'),
        ('categories', '0002_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_positions',
            field=models.ManyToManyField(blank=True, related_name='selected_by_workers', to='categories.position', verbose_name='Tanlangan lavozimlar (5 tagacha)'),
        ),
    ]
