# Generated by Django 6.1 on 2026-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_selected_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aniq manzil / Joylashuv matni'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS Uzunlik (Longitude)'),
        ),
    ]
