# Generated by Django 6.1 on 2026-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_address_title_user_latitude_user_longitude'),
        ('categories', '0002_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman / Shahar'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('daily', 'Bir martalik / Kunbay'), ('permanent', 'Doimiy ish'), ('both', 'Ikkalasi ham')], default='both', max_length=20, verbose_name='Bandlik turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Mahalla, ko'cha, uy raqami"),
        ),
        migrations.AddField(
            model_name='user',
            name='work_schedule',
            field=models.CharField(choices=[('day_shift', '09:00 - 18:00 (Kunduzgi)'), ('24_7', '24/7 (Istalgan vaqtda / Shoshilinch)'), ('flexible', 'Erkin grafik')], default='flexible', max_length=20, verbose_name='Ish vaqti rejimi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_positions',
            field=models.ManyToManyField(blank=True, related_name='selected_by_workers', to='categories.position', verbose_name='Tanlangan lavozimlar (10 tagacha)'),
        ),
    ]
