# Generated by Django 6.1 on 2026-09-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_age_user_district_user_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_jobs_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bajarilgan ishlar soni'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name="Ro'yxatdan to'liq o'tganmi"),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_setting',
            field=models.CharField(choices=[('all', 'Barcha xabarlar yoqiq'), ('night_mute', 'Tungi rejim (22:00 dan keyin ovozsiz)'), ('off', "Bildirishnomalarni butunlay o'chirish")], default='all', max_length=20, verbose_name='Bildirishnoma sozlamasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Taklif / Shikoyat matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi taklif/shikoyati',
                'verbose_name_plural': 'Foydalanuvchi taklif va shikoyatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rasm tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta portfolio rasmi',
                'verbose_name_plural': 'Usta portfolio rasmlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mijoz telefoni')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('comment', models.TextField(verbose_name='Sharh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta sharhi',
                'verbose_name_plural': 'Usta sharhlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
