# Generated by Django 6.1 on 2026-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_completed_jobs_count_user_is_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_profile_update',
            field=models.BooleanField(default=False, verbose_name="Qayta to'ldirish talab qilinadimi"),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_update_reason',
            field=models.TextField(blank=True, null=True, verbose_name="Qayta to'ldirish sababi / Admin izohi"),
        ),
    ]
