# Generated by Django 6.1 on 2026-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_needs_profile_update_user_profile_update_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_update_fields',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qayta to'ldirilishi kerak bo'lgan maydonlar (vergul bilan)"),
        ),
    ]
