# Generated by Django 6.1 on 2026-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_profile_update_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_tabs',
            field=models.CharField(blank=True, default='all', max_length=500, null=True, verbose_name="Ruxsat etilgan bo'limlar"),
        ),
    ]
