# Generated by Django 6.1 on 2026-08-25 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='categories.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('TELEGRAM_BOT', 'Telegram Bot'), ('CALL_CENTER', 'Call Center')], default='CALL_CENTER', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Ish xizmati', max_length=255),
        ),
    ]
