# Generated by Django 6.1 on 2026-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_category_order_customer_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_format',
            field=models.CharField(choices=[('OFFLINE', 'Joyiga borish (Offline)'), ('ONLINE', 'Masofaviy (Online)')], default='OFFLINE', max_length=20),
        ),
    ]
