# Generated by Django 6.1 on 2026-09-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_remove_category_description_and_more'),
        ('locations', '0002_region'),
        ('orders', '0003_order_work_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('daily', 'Bir martalik / Kunbay'), ('permanent', 'Doimiy ish (oylik)')], default='daily', max_length=20, verbose_name='Bandlik turi')),
                ('custom_position_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Boshqa mutaxassislik nomi')),
                ('description', models.TextField(verbose_name='Ish tavsifi va sharoiti')),
                ('photo_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obyekt rasmi (Telegram File ID)')),
                ('workers_count', models.CharField(default='1 nafar', max_length=50, verbose_name='Kerakli ishchilar soni')),
                ('gender_requirement', models.CharField(choices=[('any', "Farqi yo'q"), ('male', 'Faqat erkak'), ('female', 'Faqat ayol')], default='any', max_length=20, verbose_name='Jinsi talabi')),
                ('start_time_type', models.CharField(choices=[('urgent', 'Tezda (Bugun / Shoshilinch)'), ('tomorrow', 'Ertaga'), ('custom', 'Aniq sana / Kelishilgan')], default='urgent', max_length=20, verbose_name='Boshlanish vaqti turi')),
                ('custom_start_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aniq boshlanish sanasi/vaqti')),
                ('is_price_negotiable', models.BooleanField(default=True, verbose_name='Narxi kelishilganmi')),
                ('price_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov summasi")),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman / Shahar')),
                ('address', models.TextField(blank=True, null=True, verbose_name="Aniq manzil / Mo'ljal")),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='GPS Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='GPS Uzunlik')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Aloqa uchun ism')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Aloqa telefoni')),
                ('contact_telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aloqa Telegram Username')),
                ('status', models.CharField(choices=[('active', 'Faol / Qidirilmoqda'), ('paused', "Vaqtincha to'xtatilgan"), ('completed', 'Ishchi topildi / Yopilgan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name="E'lon holati")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='Откликлар soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='categories.category', verbose_name='Asosiy soha')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_posts', to=settings.AUTH_USER_MODEL, verbose_name='Ish beruvchi')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='categories.position', verbose_name='Mutaxassislik / Lavozim')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='locations.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': "Ish e'loni",
                'verbose_name_plural': "Ish e'lonlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi / Usta')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='orders.jobpost', verbose_name="Ish e'loni")),
            ],
            options={
                'verbose_name': 'Ishga murojaat (Отклик)',
                'verbose_name_plural': 'Ishga murojaatlar (Откликлар)',
                'ordering': ['-applied_at'],
                'unique_together': {('job_post', 'worker')},
            },
        ),
    ]
