# Generated by Django 6.1 on 2026-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_jobpost_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='proposal_message',
            field=models.TextField(blank=True, null=True, verbose_name='Usta taklif xabari'),
        ),
    ]
