# Generated by Django 6.1 on 2026-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_jobapplication_proposal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_deleted_by_employer',
            field=models.BooleanField(default=False, verbose_name="Ish beruvchi tomonidan o'chirilgan"),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_deleted_by_worker',
            field=models.BooleanField(default=False, verbose_name="Ishchi tomonidan o'chirilgan"),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Ish taklifi sifatida yuborilgan (5km yoki moslik)'),
        ),
    ]
