# Generated by Django 6.1 on 2026-09-02 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': "Soha / Yo'nalish", 'verbose_name_plural': "Sohalar va Yo'nalishlar"},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_oz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номи (Ўзбек Кирилл)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название (Русский)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='', max_length=150, verbose_name="Nomi (O'zbek Lotin)"),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🛠️', max_length=30, verbose_name='Ikonka (Emoji)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=150, verbose_name="Lavozim nomi (O'zbek Lotin)")),
                ('name_oz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Лавозим номи (Ўзбек Кирилл)')),
                ('name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название должности (Русский)')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Position Name (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='categories.category', verbose_name='Tegishli Soha')),
            ],
            options={
                'verbose_name': 'Lavozim / Mutaxassislik',
                'verbose_name_plural': 'Lavozimlar va Mutaxassisliklar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
