# Generated by Django 6.1 on 2026-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=150, verbose_name="Viloyat/Shahar (O'zbek Lotin)")),
                ('name_oz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вилоят/Шаҳар (Ўзбек Кирилл)')),
                ('name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Область/Город (Русский)')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Region/City (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Viloyat / Hudud',
                'verbose_name_plural': 'Viloyatlar va Hududlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
