# Generated by Django 6.1 on 2026-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='about_text',
            field=models.TextField(blank=True, default="Full-Xizmat — O'zbekiston bo'ylab usta va mijozlarni tezkor bog'lovchi yagona professional xizmat platformasi.\n\nIshonchli ustalar, kafolatlangan xizmat va shaffof narxlar!"),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='call_center_phone',
            field=models.CharField(blank=True, default='+998 (71) 200-00-00', max_length=50),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='help_text',
            field=models.TextField(blank=True, default="• Buyurtma Berish: Kerakli xizmat turini tanlab, oson buyurtma qoldiring.\n• Ish Qidirish: Ustalar yangi buyurtmalarni qabul qilishi mumkin.\n• Profilim: Ma'lumotlaringizni ko'ring va tahrirlang.\n• Buyurtmalarim: Buyurtmalar holatini kuzatib boring."),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='welcome_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='welcome_text',
            field=models.TextField(blank=True, default="Assalomu alaykum, {first_name}! 👋\n\nFull-Xizmat usta va xizmatlar platformasining rasmiy botiga xush kelibsiz!\n\nQuyidagi menyu orqali kerakli bo'limni tanlang:"),
        ),
    ]
