# Generated by Django 6.1 on 2026-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0002_botconfig_about_text_botconfig_call_center_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='client_bot_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='credit_price_sum',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='initial_free_credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='job_posting_cost_credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='monetization_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='worker_bot_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
