# Generated by Django 6.1 on 2026-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0003_botconfig_client_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='app_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ilova havolasi (URL)'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='app_url_enabled',
            field=models.BooleanField(default=False, verbose_name='Ilovaga kirish tugmasi faolmi'),
        ),
    ]
