# Generated by Django 6.1 on 2026-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0004_botconfig_app_url_botconfig_app_url_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='client_bot_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ish beruvchi bot havolasi'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='worker_bot_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Usta bot havolasi'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='about_text',
            field=models.TextField(blank=True, default="24/7-ishlar — O'zbekiston bo'ylab usta va mijozlarni tezkor bog'lovchi yagona professional xizmat platformasi.\n\nIshonchli ustalar, kafolatlangan xizmat va shaffof narxlar!"),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='welcome_text',
            field=models.TextField(blank=True, default="Assalomu alaykum, {first_name}! 👋\n\n24/7-ishlar usta va ishlar platformasining rasmiy botiga xush kelibsiz!\n\nQuyidagi menyu orqali kerakli bo'limni tanlang:"),
        ),
    ]
