# Generated by Django 6.1 on 2026-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0005_botconfig_client_bot_url_botconfig_worker_bot_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='project_name',
            field=models.CharField(blank=True, default='24/7-ishlar', max_length=150, verbose_name='Loyiha (Brend) nomi'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='about_text',
            field=models.TextField(blank=True, default="{project_name} — O'zbekiston bo'ylab usta va mijozlarni tezkor bog'lovchi yagona professional xizmat platformasi.\n\nIshonchli ustalar, kafolatlangan xizmat va shaffof narxlar!"),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='welcome_text',
            field=models.TextField(blank=True, default="Assalomu alaykum, {first_name}! 👋\n\n{project_name} usta va ishlar platformasining rasmiy botiga xush kelibsiz!\n\nQuyidagi menyu orqali kerakli bo'limni tanlang:"),
        ),
    ]
