# Generated by Django 6.1 on 2026-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0006_botconfig_project_name_alter_botconfig_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='project_name',
            field=models.CharField(blank=True, default='IshBazari', max_length=150, verbose_name='Loyiha (Brend) nomi'),
        ),
    ]
